### ISSUE TITLE
Issue with DMS migration to DynamoDb

### ISSUE THREAD

**Issue by vikmn** [aws-samples/aws-dms-cdc-sample#1]
Hi,
i have tried to use the above sample and tweak it to migrate from sql server rds db to dynamodb.
However i seem to encounter issues. I have created a releavnt targe for dynamodb and a subsequent object mapping as per instructions at https://docs.aws.amazon.com/dms/latest/userguide/CHAP_Target.DynamoDB.html
the related sections in my cloudformation template
 ``` YAML
 myDynamoDBTable: 
    Type: AWS::DynamoDB::Table
    Properties: 
      AttributeDefinitions: 
        - 
          AttributeName: "Id"
          AttributeType: "N"
      KeySchema: 
        - 
          AttributeName: "Id"
          KeyType: "HASH"
      ProvisionedThroughput: 
        ReadCapacityUnits: "1"
        WriteCapacityUnits: "1"
      TableName: "table-name"
      GlobalSecondaryIndexes: 
        - 
          IndexName: "myGSI"
          KeySchema: 
            - 
              AttributeName: "Id"
              KeyType: "HASH"
          Projection: 
            NonKeyAttributes: 
              - "Name"
              - "Balance"
              - "Phone"
              - "IsActive"
            ProjectionType: "INCLUDE"
          ProvisionedThroughput:
            ReadCapacityUnits: "1"
            WriteCapacityUnits: "1"
  DMSEndpointDDB:
    Type: 'AWS::DMS::Endpoint'
    Properties:
      EndpointType: target
      EngineName: dynamodb
      DynamoDbSettings:
        ServiceAccessRoleArn: !GetAtt
          - DMSExecutionRole
          - Arn
    DependsOn:
      - myDynamoDBTable
DynamoDbMigration:
    Type: 'AWS::DMS::ReplicationTask'
    Properties:
      MigrationType: full-load-and-cdc
      ReplicationInstanceArn: !Ref DMSReplicationInstance
      SourceEndpointArn: !Ref DMSEndpoint
      TableMappings: >-
        {
          "rules": [
            {
              "rule-type": "selection",
              "rule-id": "1",
              "rule-action": "include",
              "object-locator": 
              {
                "schema-name": "%",
                "table-name": "CustomerInformation"
              },
              "rule-name": "1"
            },
            {
              "rule-type": "object-mapping",
              "rule-id": "2",
              "rule-action": "map-record-to-record",
              "object-locator": 
              {
                "schema-name": "dbo",
                "table-name": "CustomerInformation"
              },
              "target-table-name": "table-name",
              "rule-name": "TransformToDDB"
            }]
        }
      TargetEndpointArn: !Ref DMSEndpointDDB
```

The template launches correctly as expected. However when i run the task i see a table error. Unfortunately inspite of enabling cloud wtach logs on the task i am unable to see the logs in cloudwatch to debug this issue. Are you able to help please?
